### PR TITLE
Add button to convolve all non fmriprep predictors. 

### PR DESCRIPTION
**Pull request by rwblair**
Also when loading an existing analysis enable all tabs if any contrasts have been made.

### CODE REVIEW

**Comment by adelavega** [comment]
Looks pretty good but I need to run the wording by @tal

**Comment by tal** [comment]
I assume you want someone else

**Comment by rwblair** [comment]
Sorry about that @tal.  paging @tyarkoni  instead.

Current wording of the button is "Select All Non-Confounds"

**Comment by adelavega** [comment]
LGTM Merging

**Pull request merged**
