### PR TITLE
Add a replace n/a with 0 transform before compilation.

### LINKED ISSUE #329: Add "replace na" a transformation (final step)
By default, NAs should be replaced by 0s after transformations. This should be a checkbox in the 'config' tab.

Or perhaps this should be a transformation, so that it is more explicit in the BIDS model.

### PR DESCRIPTION
**Pull request by rwblair**
fixes #329. Looks to see if a transformation exists that has all the predictors in it and replaces 'n/a' with 0. If it doesn't exist that transformation is added on submission for compilation.

### CODE REVIEW

**Comment by tyarkoni** [comment]
Replacing n/a with 0 has the potential to dramatically change the design matrix in ways the user won't be expecting. Why can't it be handled with a `DropNA` transformation?

**Comment by tyarkoni** [comment]
I think I'd prefer to fail gracefully if there are any `NaN` values in the design matrix... maybe this can be part of a check before compilation, and if `NaN`s are found, the user gets an error message telling them to explicitly call `DropNA`.

**Comment by tyarkoni** [comment]
I guess a related question is, where are `NaN` values being introduced? I assume they're coming from features we've extracted and are storing in the DB... if there are some places where null values are common, maybe the best solution is for us to handle that in preprocessing. I vaguely recall discussing this in the past, but don't remember the conclusion of those discussions...

**Comment by adelavega** [comment]
Yes, actually this is the solution we came up with a while ago (although I can't remember the details either...), but looking at it now I had the same concerns you raise.

There are many places `n/a`s could be found. Two examples would be `FramewiseDisplacement` and another is `subtlexusfrequency_Lg10WF`.

I think for some it makes sense to drop in advance from the db, such as `FramewiseDisplacement` (because I can't imagine why anyone would want to fill those with a value), but for others such as frequency its up to the user to deal with that correctly. 
Unless we waned to be more heavy handed and do something like pre-scale + replace n/a with zero for all runs in the db. This would make model building easier but would be quite opinionated and more work for us to mantain.

I agree the best solution is to catch this at the report stage and offer a suggestion. And maybe for *some* variables preprocessing would make sense. This can come as part of a larger PR to give more useful error messages / warnings at the report stage. 

Closing this for now. Sorry for the confusion @rwblair !

**Pull request closed without merging**
