### PR TITLE
fixes for #442 and #429

### PR DESCRIPTION
**Pull request by rwblair**
also includes changes from recently closed PR to fix first design matrix opening by default.

### CODE REVIEW

**Comment by rwblair** [comment]
Tested the command that failed in travis: `python -c "import imageio; imageio.plugins.ffmpeg.download()"`  locally and it worked, so the ffmpeg url is still up and active.

**Comment by adelavega** [comment]
So travis is just acting funky then?

**Comment by rwblair** [comment]
I think so, its strange because the ffmpeg file is hosted on github.com, and we are able to clone from github.com seems like it shouldn't be a connectivity issue.

Guess I'll wait a little bit and try re-running see if it clears up. Wish travis had ssh access.

**Comment by rwblair** [comment]
@adelavega ok I think I have fixed that, and another issue of applying filters one after another that I must of introduced.

**Comment by adelavega** [comment]
Sweet

**Pull request merged**
