### PR TITLE
add private boolean to predictor collections backend.

### PR DESCRIPTION
**Pull request by rwblair**

### CODE REVIEW

**Comment by rwblair** [comment]
@adelavega could you generate migration for this on server? My migrations are in state that might cause problems if I pushed them to repo.

**Comment by rwblair** [comment]
Would there be any issue with putting a FK from to predictor_collection directly in the predictor model? Do we ever for see a predictor belonging to multiple collection?

**Comment by adelavega** [comment]
I should probably also implement the logic for only returing relevant predictors on a user by user basis.

**Comment by adelavega** [comment]
OK, I merged to master the migration. I think the only thing needed now is the Schema change

**Comment by adelavega** [comment]
Closing this in favor of #631

**Pull request closed without merging**
