### PR TITLE
[WIP] poll analysis status

### PR DESCRIPTION
**Pull request by rwblair**
For #115 

Opening a PR so we can test discuss this. This style of polling is an old way of doing things, but its nice in that we don't have to change the server at all.

Right now it is only active for people who are logged in, and it only monitors analyses that they own.

Need to test to see if this causes any issues with memory usage over  the long term.

An alternative would be socketio which has a flask library and uses web sockets. can send updates to the client side when status changes are made.

### CODE REVIEW

**Comment by tyarkoni** [comment]
I'd say if it works as-is right now, and it's not obvious that it's going to spring giant memory leaks, it's fine to leave it as-is, assuming there are other things to work on. We can revisit it later if scalability becomes an issue.

**Comment by adelavega** [comment]
I've increased the gunicorn worker timeout to 120s. This should reduce problems for many analyses, but unfortunately (for me), many analyses will still timeout. In the long term I think I need to get SQL (+Flask models etc..) working on Celery...

**Comment by rwblair** [comment]
Still needed on this PR:

-  Only show changes on Fail/Pass (not submitting etc)
-  Grey out generate button immediately after being pressed
-  Selecting a new predictor in the predictor tab should enable the save button

**Comment by rwblair** [comment]
Latest commits should address my previous comments issues.

**Pull request merged**
