### PR TITLE
Various UI improvements + Pybids 0.12.3

### LINKED ISSUE #770: Reports: Throw warning when n/a present
Currently, for BERT surprisal if I don't replace the n/as, the  variable turns to all n/as

### LINKED ISSUE #795: clean up API
Some possible minor improvements to API usability:

- Remove `run_id`s return from `/api/datasets`. It seems unnecessary as usually you want run_ids for a specific task, not the whole dataset.
- Allow `/api/predictor` to be queried without `run_ids` and instead `dataset_id` and/or `task_id`. 
Alternatively, add the following: `/api/dataset/<id>/task/<id>/predictors`

### LINKED ISSUE #823: allow unititled analyses?
should we allow analyses to not have a name? 
names can always be given later, and i often find myself struggling with name when im just trying things out.

maybe we can allow users to create without a name, but a name must be given prior to compliation?

### LINKED ISSUE #833: make hash_id 8 chars and case insensitive
to prevent case related clashes.

### PR DESCRIPTION
**Pull request by adelavega**
- Closes #823 
    - Allow united analyses until compilation (then backend rejects compilation until you provide a name).
-  Closes #833 and #838 
   - Switch to 5 char UUID, checking for clashes upon generation
- Closes #770 by throwing warning if any n/as are found in variables. It suggesting using the Scale transformation to remove n/as.
 - Default option for scale is to replace n/a with 0 after scaling.  
- Closes #795. Minor API improvements.

### CODE REVIEW

**Comment by adelavega** [comment]
@rwblair can you also tackle #826 on this one?

**Comment by adelavega** [comment]
For the `n/a` problem:
Scale - make replace after scale default value
Add docs in warning about doing this.

**Comment by adelavega** [comment]
Fixed #821 by using new version of pybids which has a fix for this. Also bumped to latest pybids version. Need to update the PIN once the official release comes through.

We should also address the fact that correlation matrix plots are not showing up in this PR.

**Comment by rwblair** [comment]
f02e32e fixes #826

**Comment by adelavega** [comment]
@rwbair just a reminder to tackle #824 tomorrow if you get a chance (in this PR if it's still open, thanks).

**Comment by adelavega** [comment]
Just to recap things left to do:
- Waiting to @tyarkoni to review my pybids PR, so we can cut a new release and PIN it here
- @rwblair we might want to look at this issue as well: #822
- @rwblair working on #824
- I'm also looking into why the corr matrix plot is not showing up.

**Pull request merged**
