### PR TITLE
September grab bag

### LINKED ISSUE #619: Remove promise resolution from constructors
These should live in componentDidMount. Main place is in the core app component that handles the inital load of public analyses and datasets.

### LINKED ISSUE #813: User generated predictors not showing up in predictor list
cc: @rwblair 

related issue: https://github.com/neuroscout/neuroscout/issues/812

### PR DESCRIPTION
**Pull request by rwblair**
- Timestamp - remove time from sort, but add full time stamp to report
- Closes #813 
- Closes #619
- Miscellanous bugs: collection list failing with no uploaded predictors, api call to neurovault failing

### CODE REVIEW

**Comment by adelavega** [comment]
Looks like the date in the analysis listing is only date-month, why not day? I think just classic MM-DD-YY would be best probably

Minor comment about the last modified date, it's really close to the (i) hover thing, which makes them seem related. 
I would say either mom the date into the body, or put the last modified date into a "Tag" to visually separate them.
It made me expect that the (i) was going to tell me about the last modified date when its just general info. 

By Tag I like the way  "PASSED" is displayed on the Status tab.

We could also just put the last modified date on the Status tab if there's more room there.

**Comment by rwblair** [comment]
Right now for date formatting I have dd-mm-yyyy

The world is a big scary place and we Americans are not making it any easier:
https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by adelavega** [comment]
loaded on server for testing. so far looks good to me, although tests are failing.

@rwblair can you tag all the issues addressed in the initial comment?

**Comment by adelavega** [comment]
Tests fixed, if you can just list those issues and I can verify all is well I think we're ready to merge

**Comment by rwblair** [comment]
Just the note that is in progress in .8 project, #813 and potentially #619 when task selecting is implemented for predictor uploads. There were a few bugs that didn't have issues that were fixed (collection list failing with no uploaded predictors, api call to neurovault failing)

**Pull request merged**
