### PR TITLE
Password retype and friends

### LINKED ISSUE #420: Store active tab when refreshing
When you refresh page of the builder (even if saved), it should go back to the tab you were on

### LINKED ISSUE #572: Have clone open directly to builder
now you just stay on same page. confusing when in public analyses.

### LINKED ISSUE #822: unable to deselect "scale design matrix"
under the review tab, it appears [I was unable to deselect "scale design matrix"](https://youtu.be/VWUGOEgAsSQ?t=1197)

### LINKED ISSUE #824: retype password on sign up
- it's fairly customary and we don't do it
- this can be purely a frontend check

### PR DESCRIPTION
**Pull request by rwblair**
fixes #822 fixes #824 fixes #420 fixes #572

### CODE REVIEW

**Comment by rwblair** [comment]
Spacing between labels and fields in sign up form maybe too far apart now, let me know if it should be tightened up.

**Comment by adelavega** [comment]
nice, ready for review?

**Comment by adelavega** [comment]
all look good for me, except that when i tried to make a new analysis, and went to the predictor tabs, refresh acted funny. i refreshed at this stage, and when it came back, it acted as if it was already compiled, and was on the "Review" tab. The report failed to generate though, because I hadn't even selected any predictors yet.

Otherwise, LGTM!

**Review by adelavega — CHANGES_REQUESTED** [review]
@rwblair all looks good except that #420 doesn't seem to fully work. I am no longer seeing the strange behavior when I do a refresh on the `Predictor` tab, but it always seems to go  back to the first tab.

It's not really a huge deal to be honest, and I think it's a bit of luxury to have that behavior, so I'd be happy to ignore it and merge, but I think your intention was for that to work, so let me know what you see.

**Pull request merged**
