### PR TITLE
Dataset list refactor

### LINKED ISSUE #689: displaying more dataset info in analysis builder
It might help to be able to see more details on the available datasets when you have to select them in neuroscout.org analysis builder. </br> Could be useful to expand the **datasets table** displayed in the **analysis builder** , potentially adding: 
- more systematic info on which modalities are available in the dataset (e.g. a yes/no value coding for presence of "auditory", "visual", "speech" info)
- duration
- TR and/or number of TRs per subject
- tasks (passive viewing/listening or other)
- dataset id used to retrieve dataset details when accessing API via pyNS
- when dataset is a subset of the linked dataset, pointer to how and why this has been done 
- reference to most relevant paper?

### PR DESCRIPTION
**Pull request by adelavega**
Closes #689 

Let's also take care of #707  and #692  here.

For now just made these small backend changes:

- `mimetype` for datasets are now sorted by id, so that the oldest stimuli for each dataset goes first. Let's display the mimetype for only that one, as that is the original stimulus.
- `TR` is now shown for tasks under datasets route.

### CODE REVIEW

**Comment by adelavega** [comment]
We could also add a `long_description` for each dataset, or `task`. Probably better for `task`.

**Comment by adelavega** [comment]
Author list sometimes was one long string. I manually updated these entries, as these are technically BIDS errors which need to be corrected prior to ingestion. In the future, check this field prior to ingestion.

**Comment by rwblair** [comment]
Length of stimuli for display.

**Comment by adelavega** [comment]
@rwblair fyi the server is live with the changes in this branch

**Comment by adelavega** [comment]
The API, I mean.

**Comment by rwblair** [comment]
I didn't end up putting any of the task information in the dataset expansion, just extended the task table to include it.

No real formatting going on in expansion still, will only show mean age, percent female, and known issues if present.

**Comment by adelavega** [comment]
I actually think the Task information might be good where it is now that I've looked at it.

My main gripes now will be aesthetic ones, but I may play around with it myself and see if I can think of other ideas

**Comment by adelavega** [comment]
- For "Average Run Length" let's just display `s` instead of `seconds`.
- Remove the (N) after subject

**Comment by adelavega** [comment]
I think I'm going to change `description` to `summary` and shorten it, then add a longer description for each dataset. This will include `known_issues` so I will get rid of that field.  The `description` will be displayed under the + button, and the `summary` where `description` is now.

I think for missing demographics we should put `n/a`, so that it doesn't look too empty. We could potentially put these in a box that says demographics.

Let's also put a complete author listing under the + button (or maybe what we were doing before that showed ~5 others, with `...` in between).

Let's preface the external link with something like `References and Links:`. 

Curation wise, I'll do the following:
- Put all author lists under the same format
- Change the descriptions/summaries
- Add long descriptions for all.
- Add missing demographics for HBN, other tasks...


Other ideas for other fields (that as in OpenNeuro for example)
- Date added (not sure if I even have that)
- Dataset DOI
- Funding

**Comment by adelavega** [comment]
Snuck in a patch for #717

**Comment by adelavega** [comment]
Okay @rwblair I think the fixed width looks good!

@rbroc will you take look at the final descriptions and propose changes as you see fit?

**Comment by adelavega** [comment]
@rwblair one minor thing here

Looks like when I unselect all runs, then select all again (in SherlockMerlin, with a task selected), the following happens:

image

**Comment by adelavega** [comment]
Otherwise, eveything else LGTM,

**Comment by rbroc** [comment]
> Okay @rwblair I think the fixed width looks good!
> 
> @rbroc will you take look at the final descriptions and propose changes as you see fit?

Looks great!
Really minor things if one wants to be super picky:
- For HBN, maybe woudn't say that only a "small" subset of participants is available (we have 142 subjects after all)
- For schematic narratives, do we also have the data from the audio-only runs? If not, I would make that clear in the short description. If yes, would fix "description" in task tab, which right now says "audiovisual watching".
- Typo in Forrest, should be "movie being present**ed** in German", I guess.

Everything else looking awesome!

**Comment by adelavega** [comment]
@rbroc I think in the Schematic Narratives, the audio only clips are played during the video stimulation within a run, so we're good.

**Pull request merged**
