### PR TITLE
[WIP] Drag, drop, and edit xforms and contrasts

### PR DESCRIPTION
**Pull request by rwblair**
addresses #415 and #96.

Contrasts view still needs work on how we want to visualize existing contrasts.

### CODE REVIEW

**Comment by adelavega** [comment]
For both Contrast and Transformation, when navigating away (either to another transformation or to another tab), save that transformation + validate. In other words, copy + show validation errors, and don't allow navigation unless errors are cleared. This includes for contrast name (allow clicking OK but show error if there is no name or if name is not unique).

**Comment by rwblair** [comment]
Backup alternative would be to notify of unsaved changes on navigating away from unsaved xform/contrast.

**Comment by rwblair** [comment]
For future reference, was seeing if its possible to apply only part of a schema to automate the validation of xforms onSave, but it looks like the BidsModelSchema would need a substantial rewrite to make this happen:
https://github.com/epoberezkin/ajv/issues/211

As of now we have hand coded all the type info for the transforms and their arguments, so for now will just be looking at the required field in each transforms schema for validation.

**Comment by adelavega** [comment]
hey, any updates on this?

**Comment by rwblair** [comment]
@adelavega take a look at this and see what you think.

**Comment by rwblair** [comment]
Ok addressed the original three bugs. Removed the search when there are less than 20 predictors to choose from. Got the weights to be closer together.

Haven't figured out how to get that label on the same line as the contrasttype.

For autocontrasts, what do we want functionality to be if inputs are added or removed after auto contrasts has been clicked? Should we automatically add new auto contrasts if they go back to the overview tab and add more inputs?

**Comment by adelavega** [comment]
Thanks!

Hmm, good question. I would say if its a check box, then yes. We could also make it a button which indicates its a one time action. I think the first option is probably best... that is auto adding if more predictors are added.

**Comment by rwblair** [comment]
Sorry missed you comment before last commit. I'll switch it back to be a checkbox and see what we can do about adding any new predictors to the the autocontrasts list when selected.

**Comment by adelavega** [comment]
I'll ask Tal his opinion this afternoon.

Relatedly, it seems that contrasts is adding weird stuff to the JSON model.

See: https://alpha.neuroscout.org/builder/wyJWA

This is a portion of the JSON Model
```
"Steps": [
    {
      "AutoContrasts": true,
      "Contrasts": [
        {
          "ConditionList": [
            "dark",
            "daylight"
          ],
          "ContrastType": "T",
          "Name": "day_vs_dark",
          "Weights": [
            1,
            -1
          ],
          "selectedPredictors": [
            {
              "description": "Clarifai image recognition label: dark",
              "extracted_feature": {
                "created_at": "2018-05-09 22:42:17.872489",
                "description": "Clarifai image recognition label: dark",
                "extractor_name": "ClarifaiAPIImageExtractor",
                "id": 13647,
                "modality": null
              },
              "id": 12787,
              "max": 0.9882182,
              "mean": 0.3242534958889997,
              "min": 0.0058510695,
              "name": "dark",
              "num_na": 0,
              "source": "ClarifaiAPIImageExtractor",
              "stddev": 0.25294245066492155
            },
            {
              "description": "Clarifai image recognition label: daylight",
              "extracted_feature": {
                "created_at": "2018-05-09 22:42:17.881578",
                "description": "Clarifai image recognition label: daylight",
                "extractor_name": "ClarifaiAPIImageExtractor",
                "id": 13648,
                "modality": null
              },
              "id": 12788,
              "max": 0.98870385,
              "mean": 0.8017381956495143,
              "min": 0.021070436,
              "name": "daylight",
              "num_na": 0,
              "source": "ClarifaiAPIImageExtractor",
              "stddev": 0.14537676107116657
            }
          ]
        }
      ],
      "Level": "Run",
```

**Pull request merged**
