### PR TITLE
Remove defunct report args

### PR DESCRIPTION
**Pull request by adelavega**
- Remove defunct arguments to generate_report

### CODE REVIEW

**Comment by adelavega** [comment]
@jsmentch this should fix your pending report issue. this is up live, can you confirm it fixes your issue?

**Comment by adelavega** [comment]
okay i'm pretty sure this is it so i'm going to go ahead and merge but let me know if this crops up again.

**Comment by jsmentch** [comment]
I'm currently having some issues accessing the site where it will go to a white screen shortly after going to https://neuroscout.org/builder or upon pressing any keys

If I try to go to that previous analysis I receive this error : TypeError: this.props.checkJWT is not a function

**Comment by adelavega** [comment]
sorry that should be fixed. i accidentally loaded a feature that is being worked on

**Comment by adelavega** [comment]
make sure to do a hard refresh if you get another error

**Comment by jsmentch** [comment]
The web interface still is hanging for me when trying to get a new report from that analysis ArqX8. Even in a new incognito window. But, if I make a new analysis wQDJ8 using some of those same uploaded predictors, there is no problem! So it may be okay

**Comment by adelavega** [comment]
What's going on here most likely is that the hung result is 'cached' for that analysis, which explains why it clears up on a new analysis.

**Pull request merged**
