### PR TITLE
Annotate ingested features, add modality/source to Predictors

### LINKED ISSUE #290: Describe / normalize ingested feature in featureschema
Currently the feature schema only applies to ExtractedFeatures. It would be useful to also add descriptions/tags/etc to ingested features such as "RT", and "fmriprep" features.

For features that may have different names across datasets, it would be nice to force them to be the same. E.g. "RT" and "reaction_time", should be "reaction_time" in two datasets.

### PR DESCRIPTION
**Pull request by adelavega**
Fixes #290 and #285

### CODE REVIEW

**Comment by adelavega** [comment]
I implemented a function to update objects in the DB against updated schemas.

There are two main limitations:
1. If the name has been changed with a regex transformation (e.g. "rt" to "reaction_time"), the schema may not match the new feature name. I was going to implement optionally matching to the new name, but those can include syntax to insert groups from original regex, so it would be possible to match in many cases. Since descriptions can also include such syntax, its essential to have the original name.
2. A solution to #1 is to avoid updating unless necessary, or adding entries to schema to cover new names, if necessary. 

This all needs to be tested, with unit tests and in a staging version of the database.

**Comment by adelavega** [comment]
Decided to keep track of `original_name` for ingested and extracted features. This solves the previous issues, except for features already in the main DB.

**Comment by adelavega** [comment]
@rwblair Predictors now have pretty descriptions (even those that dont have an Extracted Feature). Remember when you get a chance to update the app to check first the Predictor field for a description, then ExtractedFeature.

**Comment by adelavega** [comment]
@tyarkoni Don't know if you wanna review this, but I added functionality to update the description, name and source of predictors already in DB according to a JSON schema. Seems to work, and will merge soon.

**Comment by tyarkoni** [comment]
Would like to, but I'm pressed for time, so go ahead and merge it and you can fill me in later. Thanks!

**Comment by adelavega** [comment]
Sounds good, no problem!

**Pull request merged**
