### PR TITLE
Add graphs to windowed extraction

### PR DESCRIPTION
**Pull request by adelavega**
To support BERT Entropy

### CODE REVIEW

**Comment by adelavega** [comment]
Okay @rbroc I've added the ability to extract Graphs using "tokenized_extractors". Tokenized extractors are those that operate on text which is combined in various ways, most commonly either by run or by a moving window of variable size.

I extracted BERT LM Entropy with a window of 25 for Merlin Movie. Feel free to take a look, although I'm not sure what else we can do to validate. Next up, I'll extract with n=10 with the following Graph:
```
[
    [{"transformer": "BertLMExtractor", "parameters": {"mask": 10, "top_n": 100}, "children": [{"transformer": "MetricExtractor", "parameters": {"functions": "scipy.stats.entropy"}}]}],
    {"window": "pre", "n": 10}
]
```

If that looks allright I'll go ahead.

Only other thing to check is that this latest chagne didn't mess up with the extraction for normal BERT as it now also has to be graph. I'll look into that tomorrow.

**Comment by rbroc** [comment]
okay @adelavega, I think we'll go for a window size of 25 words, with: `top_n=100`, mask=24, `return_softmax=True` and, I guess, `framework='tf'`. `MetricExtractor `takes `functions='scipy.stats.entropy'`. Note that the mask argument is equal window_size - 1, as what we're doing here is masking the last word (indexing starts at 0) in a sequence and try to predict it based on the previous words. 

One small issue. I have been trying to check the extracted values for Merlin with window size 25, `top_n=100`, `mask=24` and `return_softmax` left to default, but I can't manage to reproduce them. Probably worth having a chat to find out why.

One more thing. Can't remember if, for the Bert encodings, we fed 25 words text chunks to the extractor and only picked the encoding for the last word, or if we averaged across all word-level encodings and assigned the resulting encoding to the next word in the transcript.
In the case of the entropy extractor, the entropy value we get should be assigned to the last word in the 25-word text chunk.

**Comment by adelavega** [comment]
About not being able to reproduce those values, maybe we can put that on hold and try again with the parameters you gave me. It's possible the index was set to the same as the window.

This actually reveals a bigger issue, which is that the result object has the `MetricExtractor` as its extractor, so I lose the parameters of the `BERT` extract in my meta-data... 

I may be able to address that within Neuroscout only, but we probably need to at some point (not super urgent though)

**Comment by adelavega** [comment]
I believe that you feed 25 word chunks to the extractor, and only pick the encoding the last word.

**Comment by adelavega** [comment]
@rbroc I have re-exracted the BERT entropy extractor. The name of the extractor is: `BERTLM_pre_25_entropy`.

It is available for Sherlock task in SherlockMerlin.

**Comment by rbroc** [comment]
ok, still can't reproduce the values. Maybe worth having a chat about it before extracting the rest.

**Comment by adelavega** [comment]
For SherlockMerlin this is the complete transcript: 

"
"how 's your going yeah good very good you have n't written a word have you you just wrote still has trust issues and you read my writing upside down you see what i mean john you 're a soldier and it 's going to take you a while to adjust to civilian life and writing a about everything that happens to you will honestly help you nothing happens to me what do you mean there 's no ruddy car he went to waterloo i 'm sorry get a cab i never get cabs i love you when get a cab my husband was a happy man lived life to the full he loved his family and his work and that he should have taken his own life in this way is a mystery and a shock to all who knew him taxi taxi i 'll be just two minutes mate what i 'm just going home to get my umbrella you can share mine two minutes all right she still dancing yeah if you can call it that did you get the car keys off her got them out of her bag where is she the body of beth davenport junior minister for transport was found late last night on a building site in greater london preliminary investigations suggest that this was suicide we can confirm that this apparent suicide closely resembles those of sir jeffrey patterson and james in the light of this these incidents are now being treated as linked the investigation is ongoing but detective inspector will take questions now detective inspector how can suicides be linked well they all took the same poison they were all found in places they had no reason to be none of them had shown any prior indication but you ca n't have serial suicides well apparently you can these three people there 's nothing that links them there 's no link we 've found yet but we 're looking for it there has to be one if you 've all got texts please ignore them it just says wrong well just ignore that if there are no more questions i 'm going to bring this session to an end if they 're suicides what are you investigating as i say these suicides are clearly linked it 's an unusual situation we 've got our best people investigating says wrong again one more question is there any chance that these are murders and if they are is this the work of a serial killer i know that you like writing about these but these do appear to be suicides we know the difference the poison was clearly yes but if they are murders how do people keep themselves safe well do n't commit suicide daily mail this is a frightening time for people but all anyone has to do is exercise reasonable precautions we are all as safe as we want to be mobile phones buzz thank you you 've got to stop him doing that he 's making us look like idiots if you can tell me how he does it i 'll stop him john john watson stamford mike stamford we were at barts together yes sorry yes mike hello yes i know i got fat no no i heard you were abroad somewhere getting shot at what happened i got shot are you still at barts then teaching now yeah bright young things like we used to be god i hate them what about you just staying in town till you get yourself sorted i ca n't afford london on an army pension could n't bear to be anywhere else that 's not the john watson i know i 'm not the john watson could n't harry help yeah like that 's going to i do n't know get a or something who 'd want me for a what you 're the second person to say that to me today who was the first how fresh just in natural causes used to work here i knew him he was nice fine we 'll start with the riding crop so bad day was it i need to know what bruises form in the next minutes a man 's alibi depends on it text me listen i was wondering maybe later when you 're finished you 're wearing lipstick you were n't wearing lipstick before i refreshed it a bit sorry you were saying i was wondering if you 'd like to have coffee black two sugars please i 'll be upstairs ok knock on door bit different from my day you 've no idea mike can i borrow your phone there 's no signal on mine and what 's wrong with the i prefer to text sorry it 's in my coat here use mine oh thank you this is an old friend of mine john watson afghanistan or iraq sorry which was it in afghanistan or iraq afghanistan sorry how did you know ah coffee thank you what happened to the lipstick it was n't working for me really it was a big improvement your too small now ok how do you feel about the violin i 'm sorry what i play the violin when i 'm thinking and sometimes i do n't talk for days on end would that bother you potential should know the worst about each other you told him about me not a word who said anything about i did told mike this morning that i must be a difficult man to find a for now here he is just after lunch with an old friend clearly just home from military service in afghanistan was n't a difficult leap how did you know about afghanistan got my eye on a nice little place in central london we ought to be able to afford it we 'll meet there tomorrow evening seven o'clock sorry got to dash i think i left my riding crop in the mortuary is that it is that what we 've only just met and we 're going to go and look at a flat problem we do n't know a thing about each other i do n't know where we 're meeting i do n't even know your name i know you 're an army doctor and you 've been home from afghanistan you 've got a brother worried about you but you wo n't go to him for help because you do n't approve of him possibly because he 's an alcoholic more likely because he recently walked out on his wife and i know that your therapist thinks your psychosomatic quite correctly i 'm afraid that 's enough to be going on with do n't you think the name 's sherlock holmes and the address is b baker street afternoon yeah he 's always like that hello ah mr holmes sherlock please well this is a prime spot must be expensive mrs hudson the landlady she 's given me a special deal owes me a a few years back her husband got himself sentenced to death in florida i was able to help out sorry you stopped her husband being executed oh no i ensured it sherlock mrs hudson dr john watson hello come in thank you shall we well this could be very nice very nice indeed yes yes i think so my thoughts precisely so i went straight ahead and moved in soon as we get all this rubbish cleaned out so this is all well obviously i can erm straighten things up a bit that 's a skull friend of mine when i say friend what do you think then dr watson there 's another bedroom upstairs if you 'll be needing two bedrooms of course we 'll be needing two oh do n't worry there 's all sorts round here mrs turner next door 's got oh sherlock the mess you 've made i looked you up on the internet last night anything interesting found your website the science of deduction what did you think you said you could identify a software designer by his tie and an airline pilot by his left thumb yes and i can read your military career in your face and your leg and your brother 's drinking habits on your mobile phone how what about these suicides then sherlock i thought that 'd be right up your street three exactly the same four there 's been a fourth and there 's something different this time a fourth where gardens what 's new about this one you would n't have come to me otherwise you know how they never leave notes yeah this one did will you come who 's on forensics anderson he does n't work well with me well he wo n't be your assistant i need an assistant will you come not in a police car i 'll be right behind thank you brilliant yes four serial suicides and now a note oh it 's christmas mrs hudson i 'll be late might need some food i 'm your landlady dear not your housekeeper something cold will do john have a cup of tea make yourself at home do n't wait up look at him dashing about my husband was just the same but you 're more the type i can tell i 'll make you that you rest your leg damn my leg sorry i 'm so sorry it 's just sometimes this bloody thing i understand dear i 've got a hip cup of be lovely thank you just this once dear i 'm not your housekeeper couple of biscuits too if you 've got em not your housekeeper you 're a doctor in fact you 're an army doctor yes any good very good seen a lot of injuries then violent deaths well yes bit of trouble too i bet of course yes enough for a lifetime far too much want to see some more oh god yes sorry mrs hudson i 'll skip the tea off out both of you impossible suicides four of them no point sitting at home when there 's finally something fun going on look at you all happy it 's not decent who cares about decent the game mrs hudson is on taxi ok you 've got questions yeah where are we going crime scene next who are you what do you do what do you think i 'd say private detective but but the police do n't go to private detectives i 'm a consulting detective only one in the world i invented the job what does that mean means when the police are out of their depth which is always they consult me the police do n't consult amateurs when i met you for the first time yesterday i said afghanistan or iraq you looked surprised yes how did you know i did n't know i saw your haircut the way you hold yourself says military but your conversation bit different from my day said trained at barts so army doctor obvious your face is tanned but no tan above the wrists you 've been abroad but not sunbathing your really bad when you walk but you do n't ask for a chair when you stand so it 's at least partly psychosomatic that says the original circumstances of the injury were traumatic wounded in action then wounded in action suntan afghanistan or iraq you said i had a therapist you 've got a psychosomatic limp of course you 've got a therapist then there 's your brother mm your phone it 's expensive email enabled player and you 're looking for a you would n't buy this it 's a gift scratches not one many over time it 's been in the same pocket as keys and coins you would n't treat your one luxury item like this so it 's had a previous owner next easy you know it already the engraving harry watson clearly a family member who 's given you his old phone not your father this is a young man 's gadget could be a cousin but you 're a war hero who ca n't find a place to live unlikely you 've got an extended family not one you 're close to so brother it is now who 's clara three kisses says it 's a romantic attachment the expense of the phone says wife not girlfriend must have given it to him recently it 's only six months old marriage in trouble then six months on he 's given it away if she 'd left him he would have kept it sentiment no he wanted rid of it he left her he gave the phone to you so he wants you to stay in touch you 're looking for cheap accommodation but you 're not going to your brother for help that says you 've got problems with him maybe you liked his wife or do n't like his drinking how can you possibly know about the drinking shot in the dark good one though power connection tiny little scuff marks round it every night he plugs it in but his hands are shaking you never see those marks on a sober man 's phone never see a without them there you go you were right i was right right about what the police do n't consult amateurs that was amazing do you think so of course it was it was extraordinary it was quite extraordinary that 's not what people normally say what do people normally say piss off did i get anything wrong harry and me do n't get on never have clara and harry split up three months ago and they 're getting a divorce and harry is a drinker spot on then i did n't expect to be right about everything harry 's short for harriet harry 's your sister look what exactly am i supposed to be doing here sister no seriously what am i doing here there 's always something hello freak i 'm here to see detective inspector why i was invited why i think he wants me to take a look well you know what i think do n't you always sally i even know you did n't make it home last night i do n't who 's this colleague of mine dr watson dr watson sergeant sally donovan old friend a how do you get a colleague did he follow you home would it be better if i just waited no here bringing him in ah anderson here we are again it 's a crime scene i do n't want it contaminated are we clear on that quite clear and is your wife away for long oh do n't pretend you worked that out somebody told you that your deodorant told me that my deodorant it 's for men well of course it 's for men i 'm wearing it so 's sergeant donovan ooh i think it just may i go in whatever you 're trying to imply i 'm not implying anything i 'm sure sally came round for a nice little chat and just happened to stay over and i assume she scrubbed your floors going by the state of her knees"
"

and the first window is:
"how 's your going yeah good very good you have n't written a word have you you just wrote still has trust issues and you read m"

**Comment by adelavega** [comment]
and the result for that first window is:
`0.00452` with onset of `137.232` and duration of `0.29`.

That should correspond to the word "my"

Although actually this looks a bit funny, onset for "my" in the original complex text object is 139.22

That could be the source of the mismatch.

**Comment by adelavega** [comment]
I tried this with BERTLM outside of neuroscout, and it's giving back the 137 onset. This seems like a problem with the extractor. 

Otherwise, the entropy value manually calculator also seems correct. 

The onset is relative to the onset of the movie in therun, which is 25.5.

So the first onset for the BERTLM extractor entropy value should be 25.5+139.22 = 164.72

In actually, since the returned onset is 137.232, then it is 162.732

The value in the `db for that onset is `0.005` which is correct. 

One issue is I'm rounding these values, so maybe I shouldn't be given their range. 

The one thing I don't understand is there are values before that onset, with really high entropy values and I'm not sure where they are coming from.

**Comment by adelavega** [comment]
1) I'm going to round to one more decimal place
2) We need to fix the onset coming from pliers, or I can force fix it in neuroscout by taking the onset from the last element and forcing it onto the result
3) Figure out where the first few values are coming from

**Comment by adelavega** [comment]
Okay, looks like for this window:
"good very good you have n't written a word have you you just wrote still has trust issues and you read my writing upside down you" which should have an onset of 143.602, the graph returns an onset of 134.863, with a value of 2.811. 

This onset is wrong, so this is probably why we're having weird results. 

I could fix this in NS, but I think it's a Pliers issue.

**Comment by adelavega** [comment]
in `/media/neuroscout-data/neuroscout/file_data` I saved two .pkls which are the ComplexTextStims that correspond to those two window slices, so you can play with it @rbroc.

**Comment by rbroc** [comment]
okay, looked into this. 

**Onset issue**
The onset issues was indeed a pliers issue with `BertLMExtractor`, sorry. I should have fixed it in this PR: https://github.com/tyarkoni/pliers/pull/397. 
The problem was that instead of picking the onset of the 24th word, it picked the onset of the 24th token, as indexing was based on BERT-tokenized text instead of words (as it should have been). 

There was also an additional issue little, namely that if the last word in the sequence (the one we want to mask) also occurred earlier in the sequence, the extractor would by default mask the first one. This should also be fixed now.
Unfortunately, this means that we'll have to re-extract also for SherlockMerlin, as there may be cases where the last word occurs twice in the text.

Could you try pulling pliers from my PR, and checking if the onset issue is fixed?

**Mismatch in values**
I still get slightly different values. We may be using different parameters for `BertLMExtractor`? I'm setting `return_softmax=True`, `top_n=100`, `framework='tf'`, `mask=24`.

**Input to BertLM**
I don't think the apostrophe is an issue. But if we could strip spaces from within the `text` field of each element of the `ComplexTextStim` that'd be great.

**Comment by adelavega** [comment]
Okay, now that BERT surprisal and BERT entropy are extracted I'm going to merge.,

**Pull request merged**
