### PR TITLE
make description/predictions editable and delay loading predictors

### PR DESCRIPTION
**Pull request by rwblair**
Fixes for #305 and #303 .

### CODE REVIEW

**Comment by rwblair** [comment]
Going to see if I can't get a loading display going for the predictors table that is sourced from an api call. Also run selection does not appear to affect predictors returned in this branch.

**Comment by rwblair** [comment]
Also includes fixes for #256 and #301 now

**Comment by adelavega** [comment]
On #294 there are two minor aesthetic issues that could be fixed

**Comment by adelavega** [comment]
Lets call it "Run number" instead of "Run ID"

**Comment by rwblair** [comment]
commit 9703d49 fixes #280

**Comment by rwblair** [comment]
predictor search now hits extractor_name, and extractor_description when present. fixes #236?

Set smoothing between 0 to 10 with a default of 5. @adelavega these values ok?

**Comment by adelavega** [comment]
Awesome, will test shortly. Yes those value are OK for now

**Comment by adelavega** [comment]
Cool. All looks good. Minor feedback (which we can address in another PR):

- Make the variable selection list a bit wider. It feels cramped now with the new column.
- Rename ExtractorName to `Source`. And If there is no extractor name, then pull from `Predictor.source`
- When there are no matches, it should say something other than "No data"

**Comment by rwblair** [comment]
I'll handle the variable selection in #284, when we move HRF to its own panel/tab, we might just want to have the predictor table take up the width, and always have the list of selected variables underneath the table except for the widest of screens.

Working on a fix for the Predictor source column and no results copy.

**Comment by adelavega** [comment]
Cool

**Comment by rwblair** [comment]
Ok barring any further comments I won't pile anything else into this pull request.

**Comment by adelavega** [comment]
Sounds god, let me know when its done and I'll test and merge

**Comment by rwblair** [comment]
Ok this is ready for testing.

**Comment by adelavega** [comment]
Looks good, source loads properly. But we can we make that columns Sortable? Also, lets put `Description` last. Even better, if the default sort was source and then feature_name.

**Comment by adelavega** [comment]
Also, it seems full text search does not search the Source column?

**Comment by rwblair** [comment]
Ok f0a1365 fixes search on source and has the table start default sorted by source then name.

**Comment by adelavega** [comment]
Perfect

**Pull request merged**
